import type {
  AnalysisSpec,
  AnalysisRun,
  Artifact,
  Claim,
  CleaningPlan,
  ColumnSchema,
  Dataset,
  DatasetVersion,
  Project,
  QualityIssue,
} from "./contracts";

const now = "2026-07-09T04:32:00Z";

export const seedProject: Project = {
  project_id: "prj_01JABC",
  name: "客户流失分析",
  description: "分析订阅客户的 30 日流失风险",
  timezone: "Asia/Shanghai",
  language: "zh-CN",
  status: "active",
  current_dataset_version_id: "dsv_03JABC",
  revision: 3,
  created_at: "2026-07-02T02:10:00Z",
  updated_at: now,
};

export const seedDataset: Dataset = {
  dataset_id: "ds_01JABC",
  project_id: seedProject.project_id,
  name: "customer_churn.xlsx",
  source_type: "xlsx",
  status: "active",
  current_version_id: "dsv_03JABC",
  version_count: 3,
  created_at: "2026-07-02T02:12:00Z",
};

export const seedVersions: DatasetVersion[] = [
  {
    version_id: "dsv_03JABC",
    dataset_id: seedDataset.dataset_id,
    project_id: seedProject.project_id,
    version_number: 3,
    status: "ready",
    kind: "cleaned",
    parent_version_id: "dsv_02JABC",
    source_file_name: "customer_churn.xlsx",
    sheet_name: "Customers",
    file_hash: `sha256:${"a1b2c3d4".padEnd(64, "9")}`,
    row_count: 82310,
    column_count: 18,
    operation_summary: "修复收入字段缺失并规范套餐类型",
    created_at: now,
  },
  {
    version_id: "dsv_02JABC",
    dataset_id: seedDataset.dataset_id,
    project_id: seedProject.project_id,
    version_number: 2,
    status: "ready",
    kind: "cleaned",
    parent_version_id: "dsv_01JABC",
    source_file_name: "customer_churn.xlsx",
    sheet_name: "Customers",
    file_hash: `sha256:${"9f82d6".padEnd(64, "6")}`,
    row_count: 81245,
    column_count: 18,
    operation_summary: "删除完全重复行",
    created_at: "2026-07-05T02:18:00Z",
  },
  {
    version_id: "dsv_01JABC",
    dataset_id: seedDataset.dataset_id,
    project_id: seedProject.project_id,
    version_number: 1,
    status: "ready",
    kind: "raw",
    parent_version_id: null,
    source_file_name: "customer_churn.xlsx",
    sheet_name: "Customers",
    file_hash: `sha256:${"5e30d1".padEnd(64, "1")}`,
    row_count: 80512,
    column_count: 18,
    operation_summary: null,
    created_at: "2026-07-02T02:12:00Z",
  },
];

export const seedColumns: ColumnSchema[] = [
  {
    name: "customer_id",
    physical_type: "string",
    semantic_type: "identifier",
    analysis_role: "entity_key",
    confidence: 0.99,
    evidence: ["字段名包含 id", "唯一率为 99.98%"],
    date_format: null,
    ordinal_values: null,
    sensitive: true,
    user_confirmed: true,
  },
  {
    name: "plan_type",
    physical_type: "string",
    semantic_type: "categorical",
    analysis_role: "feature",
    confidence: 0.97,
    evidence: ["唯一值数量为 3"],
    date_format: null,
    ordinal_values: null,
    sensitive: false,
    user_confirmed: true,
  },
  {
    name: "monthly_fee",
    physical_type: "float",
    semantic_type: "currency",
    analysis_role: "feature",
    confidence: 0.96,
    evidence: ["字段名包含 fee", "数值范围稳定"],
    date_format: null,
    ordinal_values: null,
    sensitive: false,
    user_confirmed: false,
  },
  {
    name: "income",
    physical_type: "float",
    semantic_type: "currency",
    analysis_role: "feature",
    confidence: 0.91,
    evidence: ["字段名包含 income", "正数连续分布"],
    date_format: null,
    ordinal_values: null,
    sensitive: true,
    user_confirmed: false,
  },
  {
    name: "churn_30d",
    physical_type: "integer",
    semantic_type: "boolean",
    analysis_role: "target",
    confidence: 0.98,
    evidence: ["仅包含 0/1", "字段名指向目标"],
    date_format: null,
    ordinal_values: null,
    sensitive: false,
    user_confirmed: true,
  },
  {
    name: "observation_date",
    physical_type: "datetime",
    semantic_type: "datetime",
    analysis_role: "time",
    confidence: 0.99,
    evidence: ["日期解析成功率 100%"],
    date_format: "YYYY-MM-DD",
    ordinal_values: null,
    sensitive: false,
    user_confirmed: true,
  },
];

const plans = ["Premium", "Basic", "Standard"] as const;
const fees = [89, 29, 59] as const;

export const seedRows: Record<string, unknown>[] = Array.from({ length: 12 }, (_, index) => ({
  customer_id: `CUST-${String(index + 1).padStart(6, "0")}`,
  plan_type: plans[index % plans.length] ?? "Standard",
  monthly_fee: fees[index % fees.length] ?? 59,
  income: "••••",
  churn_30d: index === 5 || index === 8 ? 1 : 0,
  observation_date: "2026-07-08",
}));

export const seedIssues: QualityIssue[] = [
  {
    issue_id: "issue_01JABC",
    dataset_version_id: "dsv_03JABC",
    issue_type: "missing_values",
    column: "income",
    severity: "medium",
    status: "open",
    title: "收入字段缺失 5.8%",
    explanation: "缺失主要集中在部分职业群体，可能影响模型稳定性。",
    metrics: { missing_count: 481, missing_ratio: 0.0584 },
    sample_rows: [],
    recommendation: "按职业分组使用中位数填补，并增加缺失指示变量。",
    decision_reason: null,
    revision: 1,
    created_at: now,
  },
  {
    issue_id: "issue_02JABC",
    dataset_version_id: "dsv_03JABC",
    issue_type: "leakage_risk",
    column: "cancel_date",
    severity: "critical",
    status: "open",
    title: "取消日期可能造成数据泄露",
    explanation: "该字段在预测时点之后才可获得，会导致验证指标虚高。",
    metrics: { target_correlation: 0.97 },
    sample_rows: [],
    recommendation: "从特征中排除 cancel_date，并确认预测时点。",
    decision_reason: null,
    revision: 1,
    created_at: now,
  },
  {
    issue_id: "issue_03JABC",
    dataset_version_id: "dsv_03JABC",
    issue_type: "duplicate_key",
    column: "customer_id",
    severity: "high",
    status: "open",
    title: "客户编号存在 12 条重复",
    explanation: "实体主键应唯一，重复值会影响分组拆分与客户计数。",
    metrics: { duplicate_count: 12, duplicate_ratio: 0.00015 },
    sample_rows: [],
    recommendation: "核查重复记录时间并保留最新一条。",
    decision_reason: null,
    revision: 2,
    created_at: now,
  },
];

export const seedCleaningPlan: CleaningPlan = {
  plan_id: "cln_01JABC",
  project_id: seedProject.project_id,
  source_version_id: "dsv_03JABC",
  result_version_id: null,
  name: "客户数据质量修复",
  status: "draft",
  operations: [
    {
      operation_id: "op_01",
      operation: "impute_missing",
      column: "income",
      parameters: { method: "median" },
      reason: "使用中位数填补收入缺失值",
      issue_ids: ["issue_01JABC"],
      estimated_affected_rows: 481,
      risk_level: "medium",
      reversible: true,
    },
    {
      operation_id: "op_02",
      operation: "drop_duplicates",
      column: "customer_id",
      parameters: { keep: "last" },
      reason: "实体主键应保持唯一",
      issue_ids: ["issue_03JABC"],
      estimated_affected_rows: 12,
      risk_level: "high",
      reversible: false,
    },
    {
      operation_id: "op_03",
      operation: "add_missing_indicator",
      column: "income",
      parameters: { name: "income_was_missing" },
      reason: "保留缺失模式供后续模型解释",
      issue_ids: ["issue_01JABC"],
      estimated_affected_rows: 481,
      risk_level: "low",
      reversible: true,
    },
  ],
  preview_artifact_id: null,
  decision: null,
  decision_reason: null,
  revision: 1,
  created_at: now,
  updated_at: now,
};

export const seedAnalysisSpec: AnalysisSpec = {
  spec_id: "spec_01JABC",
  project_id: seedProject.project_id,
  revision: 2,
  status: "draft",
  name: "30 日客户流失预测",
  dataset_version_id: "dsv_03JABC",
  task: "binary_classification",
  target: "churn_30d",
  entity_key: "customer_id",
  time_column: "observation_date",
  prediction_time_description: "在观察日结束时，预测客户未来 30 日内是否流失。",
  split_strategy: "stratified",
  group_column: null,
  metrics: ["roc_auc", "f1", "precision", "recall"],
  included_columns: ["plan_type", "monthly_fee", "income"],
  excluded_columns: ["customer_id", "observation_date", "cancel_date"],
  random_seed: 42,
  causal_interpretation_allowed: false,
  validation_warnings: ["cancel_date 在预测时点之后产生，已排除。"],
  created_at: now,
  updated_at: now,
};

function step(stepId: string, name: string, order: number, status: AnalysisRun["steps"][number]["status"]) {
  return {
    step_id: stepId,
    name,
    tool_name: "datatrace_pipeline",
    tool_version: "1.0.0",
    status,
    order,
    started_at: status === "pending" ? null : now,
    completed_at: status === "succeeded" ? now : null,
    artifact_ids: status === "succeeded" ? [`art_0${order}JABC`] : [],
    error: null,
  };
}

export const seedRuns: AnalysisRun[] = [
  {
    run_id: "run_01JABC",
    project_id: seedProject.project_id,
    dataset_version_id: "dsv_03JABC",
    analysis_spec_id: "spec_01JABC",
    source_run_id: null,
    run_kind: "full",
    status: "succeeded",
    progress: 100,
    current_step_id: null,
    steps: [
      step("step_01", "数据准备", 1, "succeeded"),
      step("step_02", "自动 EDA", 2, "succeeded"),
      step("step_03", "基线模型", 3, "succeeded"),
      step("step_04", "结果验证", 4, "succeeded"),
      step("step_05", "证据生成", 5, "succeeded"),
    ],
    environment: { python: "3.12", pipeline: "1.0.0" },
    created_at: "2026-07-09T04:32:00Z",
    started_at: "2026-07-09T04:32:05Z",
    completed_at: "2026-07-09T04:37:00Z",
    error: null,
  },
  {
    run_id: "run_01IABC",
    project_id: seedProject.project_id,
    dataset_version_id: "dsv_03JABC",
    analysis_spec_id: "spec_02JABC",
    source_run_id: null,
    run_kind: "eda",
    status: "running",
    progress: 64,
    current_step_id: "step_03",
    steps: [
      step("step_01", "数据准备", 1, "succeeded"),
      step("step_02", "自动 EDA", 2, "succeeded"),
      step("step_03", "基线模型", 3, "running"),
      step("step_04", "结果验证", 4, "pending"),
      step("step_05", "证据生成", 5, "pending"),
    ],
    environment: { python: "3.12", pipeline: "1.0.0" },
    created_at: "2026-07-09T03:58:00Z",
    started_at: "2026-07-09T03:58:04Z",
    completed_at: null,
    error: null,
  },
  {
    run_id: "run_01HABC",
    project_id: seedProject.project_id,
    dataset_version_id: "dsv_02JABC",
    analysis_spec_id: "spec_03JABC",
    source_run_id: null,
    run_kind: "eda",
    status: "failed",
    progress: 42,
    current_step_id: "step_02",
    steps: [
      step("step_01", "数据准备", 1, "succeeded"),
      { ...step("step_02", "自动 EDA", 2, "failed"), error: {
        code: "SCHEMA_CONFLICT",
        message: "字段类型与分析计划不兼容",
        request_id: "req_mock",
        retryable: false,
        details: { column: "monthly_fee" },
      } },
    ],
    environment: { python: "3.12", pipeline: "0.9.0" },
    created_at: "2026-07-08T09:05:00Z",
    started_at: "2026-07-08T09:05:04Z",
    completed_at: "2026-07-08T09:11:00Z",
    error: {
      code: "SCHEMA_CONFLICT",
      message: "字段类型与分析计划不兼容",
      request_id: "req_mock",
      retryable: false,
      details: { column: "monthly_fee" },
    },
  },
];

export const seedArtifacts: Artifact[] = Array.from({ length: 14 }, (_, index) => ({
  artifact_id: `art_${String(index + 1).padStart(2, "0")}JABC`,
  project_id: seedProject.project_id,
  run_id: "run_01JABC",
  dataset_version_id: "dsv_03JABC",
  type: index < 4 ? "metric" : index < 9 ? "chart" : "table",
  name: index === 0 ? "基线模型指标" : index === 4 ? "流失特征重要性" : index === 9 ? "分群指标明细" : `证据产物 ${index + 1}`,
  producer: index < 4 ? "quality_summary" : "auto_eda",
  producer_version: "1.0.0",
  status: "ready",
  parameters: {},
  result: index === 0
    ? { metrics: { "ROC-AUC": 0.842, F1: 0.701, Precision: 0.735, Recall: 0.671 } }
    : index === 4
      ? { labels: ["近30天未登录", "支付失败次数", "近7天活跃天数", "平均会话时长"], values: [0.137, 0.098, 0.087, 0.058] }
      : { value: index + 1 },
  preview: index === 9 ? { columns: ["客群", "样本数", "流失率"], rows: [["高风险", 8452, "32.8%"], ["中风险", 21008, "14.6%"], ["低风险", 52850, "3.2%"]] } : null,
  checksum: `sha256:${String(index).padEnd(64, "0")}`,
  downloadable: true,
  created_at: now,
}));

export const seedClaims: Claim[] = [
  {
    claim_id: "claim_01JABC",
    project_id: seedProject.project_id,
    run_id: "run_01JABC",
    dataset_version_id: "dsv_03JABC",
    text: "近 30 天未登录是客户流失的最强预测因素。",
    level: 3,
    evidence_ids: ["art_01JABC", "art_05JABC"],
    limitations: ["这是模型相关性解释，不构成因果结论。", "结果仅适用于当前样本时间窗口。"],
    validation_status: "passed",
    validation_messages: ["指标与图表数值一致", "证据版本绑定完整"],
    publication_status: "published",
    created_at: now,
  },
  {
    claim_id: "claim_02JABC",
    project_id: seedProject.project_id,
    run_id: "run_01JABC",
    dataset_version_id: "dsv_03JABC",
    text: "支付失败次数增加会显著提高流失风险。",
    level: 3,
    evidence_ids: ["art_05JABC", "art_10JABC"],
    limitations: ["支付渠道覆盖并不完整。"],
    validation_status: "passed",
    validation_messages: ["证据链校验通过"],
    publication_status: "published",
    created_at: now,
  },
  {
    claim_id: "claim_03JABC",
    project_id: seedProject.project_id,
    run_id: "run_01JABC",
    dataset_version_id: "dsv_03JABC",
    text: "高价值客户对客服响应时长更敏感。",
    level: 4,
    evidence_ids: ["art_10JABC"],
    limitations: ["高价值客户样本占比较低。"],
    validation_status: "passed",
    validation_messages: ["表格证据存在，但置信度为中等"],
    publication_status: "draft",
    created_at: now,
  },
];
