"""add analysis workflow metadata

Revision ID: 0d903f0dacf9
Revises: 0001_initial_foundation
Create Date: 2026-07-09 13:36:08.205318
"""

from collections.abc import Sequence

import app.persistence.types
import sqlalchemy as sa
from alembic import op

revision: str = "0d903f0dacf9"
down_revision: str | Sequence[str] | None = "0001_initial_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_specs",
        sa.Column("spec_revision_id", sa.String(length=50), nullable=False),
        sa.Column("spec_id", sa.String(length=40), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("task", sa.String(length=32), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=True),
        sa.Column("entity_key", sa.String(length=255), nullable=True),
        sa.Column("time_column", sa.String(length=255), nullable=True),
        sa.Column("prediction_time_description", sa.Text(), nullable=True),
        sa.Column("split_strategy", sa.String(length=16), nullable=False),
        sa.Column("group_column", sa.String(length=255), nullable=True),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("included_columns_json", sa.JSON(), nullable=False),
        sa.Column("excluded_columns_json", sa.JSON(), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("causal_interpretation_allowed", sa.Boolean(), nullable=False),
        sa.Column("validation_warnings_json", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=160), nullable=False),
        sa.Column("created_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "split_strategy IN ('none', 'random', 'stratified', 'temporal', 'group')",
            name="ck_analysis_spec_split",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'confirmed', 'superseded')", name="ck_analysis_spec_status"
        ),
        sa.CheckConstraint(
            "task IN ('descriptive', 'comparison', 'statistical_test', 'binary_classification', 'multiclass_classification', 'regression')",
            name="ck_analysis_spec_task",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_versions.version_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.project_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("spec_revision_id"),
        sa.UniqueConstraint("spec_id", "revision", name="uq_analysis_spec_revision"),
    )
    with op.batch_alter_table("analysis_specs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_analysis_spec_project_created", ["project_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_analysis_spec_version_status", ["dataset_version_id", "status"], unique=False
        )

    op.create_table(
        "column_schemas",
        sa.Column("column_schema_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("ordinal_position", sa.Integer(), nullable=False),
        sa.Column("physical_type", sa.String(length=24), nullable=False),
        sa.Column("semantic_type", sa.String(length=32), nullable=False),
        sa.Column("analysis_role", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.Column("profile_json", sa.JSON(), nullable=False),
        sa.Column("date_format", sa.String(length=128), nullable=True),
        sa.Column("ordinal_values_json", sa.JSON(), nullable=True),
        sa.Column("sensitive", sa.Boolean(), nullable=False),
        sa.Column("user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "analysis_role IN ('feature', 'target', 'entity_key', 'time', 'identifier', 'text', 'excluded', 'undecided')",
            name="ck_column_schema_analysis_role",
        ),
        sa.CheckConstraint(
            "physical_type IN ('integer', 'float', 'string', 'boolean', 'datetime', 'binary', 'unknown')",
            name="ck_column_schema_physical_type",
        ),
        sa.CheckConstraint(
            "semantic_type IN ('numeric', 'categorical', 'datetime', 'boolean', 'identifier', 'text', 'currency', 'percentage', 'ordinal', 'geographic_code', 'unknown')",
            name="ck_column_schema_semantic_type",
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_column_schema_confidence"),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_versions.version_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.project_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("column_schema_id"),
        sa.UniqueConstraint("dataset_version_id", "name", name="uq_column_schema_version_name"),
    )
    with op.batch_alter_table("column_schemas", schema=None) as batch_op:
        batch_op.create_index(
            "ix_column_schema_version_role", ["dataset_version_id", "analysis_role"], unique=False
        )

    op.create_table(
        "conversation_summaries",
        sa.Column("summary_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("conversation_id", sa.String(length=80), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=40), nullable=True),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("structured_context_json", sa.JSON(), nullable=False),
        sa.Column("last_message_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_versions.version_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.project_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("summary_id"),
        sa.UniqueConstraint("project_id", "conversation_id", name="uq_conversation_summary"),
    )
    with op.batch_alter_table("conversation_summaries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_conversation_summary_project_updated", ["project_id", "updated_at"], unique=False
        )

    op.create_table(
        "user_decisions",
        sa.Column("decision_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("subject_id", sa.String(length=160), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("created_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.project_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    with op.batch_alter_table("user_decisions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_decision_object", ["object_type", "object_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_user_decision_project_created", ["project_id", "created_at"], unique=False
        )

    op.create_table(
        "analysis_runs",
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=40), nullable=False),
        sa.Column("analysis_spec_revision_id", sa.String(length=50), nullable=False),
        sa.Column("source_run_id", sa.String(length=40), nullable=True),
        sa.Column("job_id", sa.String(length=40), nullable=True),
        sa.Column("run_kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("current_step_id", sa.String(length=40), nullable=True),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("environment_json", sa.JSON(), nullable=False),
        sa.Column("error_json", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.String(length=160), nullable=False),
        sa.Column("created_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("started_at", app.persistence.types.UTCDateTime(), nullable=True),
        sa.Column("completed_at", app.persistence.types.UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "run_kind IN ('eda', 'analysis', 'model', 'full')", name="ck_analysis_run_kind"
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'blocked', 'succeeded', 'failed', 'cancelled')",
            name="ck_analysis_run_status",
        ),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name="ck_analysis_run_progress"),
        sa.ForeignKeyConstraint(
            ["analysis_spec_revision_id"], ["analysis_specs.spec_revision_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_versions.version_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.project_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_run_id"], ["analysis_runs.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("run_id"),
    )
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_analysis_run_project_created", ["project_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_analysis_run_version_status", ["dataset_version_id", "status"], unique=False
        )

    op.create_table(
        "analysis_steps",
        sa.Column("step_id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("tool_name", sa.String(length=160), nullable=True),
        sa.Column("tool_version", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("parameters_json", sa.JSON(), nullable=False),
        sa.Column("error_json", sa.JSON(), nullable=True),
        sa.Column("started_at", app.persistence.types.UTCDateTime(), nullable=True),
        sa.Column("completed_at", app.persistence.types.UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'skipped', 'blocked', 'cancelled')",
            name="ck_analysis_step_status",
        ),
        sa.ForeignKeyConstraint(["run_id"], ["analysis_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("step_id"),
        sa.UniqueConstraint("run_id", "position", name="uq_analysis_step_position"),
    )
    with op.batch_alter_table("analysis_steps", schema=None) as batch_op:
        batch_op.create_index("ix_analysis_step_run_status", ["run_id", "status"], unique=False)

    op.create_table(
        "artifacts",
        sa.Column("artifact_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=True),
        sa.Column("dataset_version_id", sa.String(length=40), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("producer", sa.String(length=160), nullable=False),
        sa.Column("producer_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("parameters_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("preview_json", sa.JSON(), nullable=True),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("checksum", sa.String(length=71), nullable=False),
        sa.Column("downloadable", sa.Boolean(), nullable=False),
        sa.Column("created_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("ready_at", app.persistence.types.UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('creating', 'ready', 'failed', 'expired')", name="ck_artifact_status"
        ),
        sa.CheckConstraint(
            "type IN ('metric', 'table', 'chart', 'model', 'file', 'log', 'comparison')",
            name="ck_artifact_type",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_versions.version_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.project_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["analysis_runs.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("artifact_id"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index("ix_artifact_run_type", ["run_id", "type"], unique=False)
        batch_op.create_index(
            "ix_artifact_version_created", ["dataset_version_id", "created_at"], unique=False
        )

    op.create_table(
        "claims",
        sa.Column("claim_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=40), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("limitations_json", sa.JSON(), nullable=False),
        sa.Column("validation_status", sa.String(length=16), nullable=False),
        sa.Column("validation_messages_json", sa.JSON(), nullable=False),
        sa.Column("publication_status", sa.String(length=16), nullable=False),
        sa.Column("created_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "publication_status IN ('draft', 'published', 'withdrawn')",
            name="ck_claim_publication_status",
        ),
        sa.CheckConstraint(
            "validation_status IN ('pending', 'passed', 'failed')",
            name="ck_claim_validation_status",
        ),
        sa.CheckConstraint("level BETWEEN 1 AND 5", name="ck_claim_level"),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_versions.version_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.project_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["analysis_runs.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("claim_id"),
    )
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.create_index(
            "ix_claim_run_validation", ["run_id", "validation_status"], unique=False
        )
        batch_op.create_index(
            "ix_claim_version_publication",
            ["dataset_version_id", "publication_status"],
            unique=False,
        )

    op.create_table(
        "claim_evidence",
        sa.Column("claim_id", sa.String(length=40), nullable=False),
        sa.Column("artifact_id", sa.String(length=40), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.artifact_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.claim_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("claim_id", "artifact_id"),
    )
    op.create_table(
        "cleaning_plans",
        sa.Column("plan_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("source_version_id", sa.String(length=40), nullable=False),
        sa.Column("result_version_id", sa.String(length=40), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("preview_artifact_id", sa.String(length=40), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.String(length=160), nullable=True),
        sa.Column("decided_at", app.persistence.types.UTCDateTime(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=160), nullable=False),
        sa.Column("created_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "decision IS NULL OR decision IN ('approve', 'reject')",
            name="ck_cleaning_plan_decision",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'awaiting_approval', 'approved', 'rejected', 'executing', 'executed', 'failed')",
            name="ck_cleaning_plan_status",
        ),
        sa.ForeignKeyConstraint(
            ["preview_artifact_id"], ["artifacts.artifact_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.project_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["result_version_id"], ["dataset_versions.version_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"], ["dataset_versions.version_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("plan_id"),
    )
    with op.batch_alter_table("cleaning_plans", schema=None) as batch_op:
        batch_op.create_index(
            "ix_cleaning_plan_project_created", ["project_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_cleaning_plan_source_status", ["source_version_id", "status"], unique=False
        )

    op.create_table(
        "validation_results",
        sa.Column("validation_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("claim_id", sa.String(length=40), nullable=False),
        sa.Column("validator", sa.String(length=160), nullable=False),
        sa.Column("validator_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.Column("created_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint("status IN ('passed', 'failed')", name="ck_validation_result_status"),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.claim_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.project_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("validation_id"),
    )
    with op.batch_alter_table("validation_results", schema=None) as batch_op:
        batch_op.create_index(
            "ix_validation_result_claim_created", ["claim_id", "created_at"], unique=False
        )

    op.create_table(
        "cleaning_operations",
        sa.Column("operation_id", sa.String(length=40), nullable=False),
        sa.Column("plan_id", sa.String(length=40), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=40), nullable=False),
        sa.Column("column_name", sa.String(length=255), nullable=True),
        sa.Column("parameters_json", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("issue_ids_json", sa.JSON(), nullable=False),
        sa.Column("estimated_affected_rows", sa.BigInteger(), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("reversible", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "operation IN ('impute_missing', 'drop_duplicates', 'cast_type', 'replace_values', 'normalize_category', 'filter_rows', 'add_missing_indicator')",
            name="ck_cleaning_operation_type",
        ),
        sa.CheckConstraint(
            "risk_level IN ('low', 'medium', 'high')", name="ck_cleaning_operation_risk"
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["cleaning_plans.plan_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("operation_id"),
        sa.UniqueConstraint("plan_id", "position", name="uq_cleaning_operation_position"),
    )
    op.create_table(
        "quality_issues",
        sa.Column("issue_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=40), nullable=False),
        sa.Column("issue_type", sa.String(length=64), nullable=False),
        sa.Column("column_name", sa.String(length=255), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("sample_rows_json", sa.JSON(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("rule_name", sa.String(length=160), nullable=False),
        sa.Column("rule_version", sa.String(length=64), nullable=False),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("resolved_by_plan_id", sa.String(length=40), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.persistence.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')", name="ck_quality_issue_severity"
        ),
        sa.CheckConstraint(
            "status IN ('open', 'accepted', 'resolved', 'ignored')", name="ck_quality_issue_status"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_versions.version_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.project_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["resolved_by_plan_id"], ["cleaning_plans.plan_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("issue_id"),
    )
    with op.batch_alter_table("quality_issues", schema=None) as batch_op:
        batch_op.create_index(
            "ix_quality_issue_project_created", ["project_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_quality_issue_version_status_severity",
            ["dataset_version_id", "status", "severity"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quality_issues", schema=None) as batch_op:
        batch_op.drop_index("ix_quality_issue_version_status_severity")
        batch_op.drop_index("ix_quality_issue_project_created")

    op.drop_table("quality_issues")
    op.drop_table("cleaning_operations")
    with op.batch_alter_table("validation_results", schema=None) as batch_op:
        batch_op.drop_index("ix_validation_result_claim_created")

    op.drop_table("validation_results")
    with op.batch_alter_table("cleaning_plans", schema=None) as batch_op:
        batch_op.drop_index("ix_cleaning_plan_source_status")
        batch_op.drop_index("ix_cleaning_plan_project_created")

    op.drop_table("cleaning_plans")
    op.drop_table("claim_evidence")
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index("ix_claim_version_publication")
        batch_op.drop_index("ix_claim_run_validation")

    op.drop_table("claims")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index("ix_artifact_version_created")
        batch_op.drop_index("ix_artifact_run_type")

    op.drop_table("artifacts")
    with op.batch_alter_table("analysis_steps", schema=None) as batch_op:
        batch_op.drop_index("ix_analysis_step_run_status")

    op.drop_table("analysis_steps")
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_analysis_run_version_status")
        batch_op.drop_index("ix_analysis_run_project_created")

    op.drop_table("analysis_runs")
    with op.batch_alter_table("user_decisions", schema=None) as batch_op:
        batch_op.drop_index("ix_user_decision_project_created")
        batch_op.drop_index("ix_user_decision_object")

    op.drop_table("user_decisions")
    with op.batch_alter_table("conversation_summaries", schema=None) as batch_op:
        batch_op.drop_index("ix_conversation_summary_project_updated")

    op.drop_table("conversation_summaries")
    with op.batch_alter_table("column_schemas", schema=None) as batch_op:
        batch_op.drop_index("ix_column_schema_version_role")

    op.drop_table("column_schemas")
    with op.batch_alter_table("analysis_specs", schema=None) as batch_op:
        batch_op.drop_index("ix_analysis_spec_version_status")
        batch_op.drop_index("ix_analysis_spec_project_created")

    op.drop_table("analysis_specs")
    # ### end Alembic commands ###
